[package]
name = "rustdrop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
base64 = "0.21.0"
bytes = "1.4.0"
pnet = "0.33.0"
portpicker = "0.1.1"
prost = "0.11.9"
zeroconf = "0.10.5"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = { version = "1.28.0", features = ["full"] }
tokio-util = "0.7.8"
aes = "0.8.2"
sha2 = "0.10.6"
hkdf = { version = "0.12.3", features = ["std"] }
hmac = { version = "0.12.1", features = ["std"] }
cbc = { version = "0.1.2", features = ["std", "alloc"] }
p256 = { version = "0.13.2", features = ["ecdh"] }
clap = { version = "4.3.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.11.9"

[dev-dependencies]
hex = "0.4.3"
tracing-test = "0.2.4"
