[package]
name = "rustdrop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
openssl = "0.10.52"
pnet = "0.33.0"
portpicker = "0.1.1"
prost = "0.11.9"
rand = "0.8.5"
zeroconf = "0.10.5"
