[package]
name = "rustdrop_daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustdrop = { version = "0.1.0", path = "../rustdrop_core" }
tokio.workspace = true
tracing-subscriber = "0.3.18"
